apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rollup
  labels:
    app: nginx-rollup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        lifecycle:
          preStop:
            exec:
              command: ['sh', '-c', 'sleep 30']
      initContainers:
      - name: busybox
        image: busybox:1.28
        command: ['sh', '-c', 'sleep 30']
