apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    app: test2
spec:
  containers:
    - image: nginx
      name: nginx
    - image: appropriate/curl
      name: curl
      command: ["sleep", "3600"]
